CREATE TABLE TEAM08.COMMON_META(
    SNDR VARCHAR(4), --消息发送者
    RCVR VARCHAR(4), --消息接收者
    SEQN NUMBER(6) PRIMARY KEY, --消息序号
    DDTM VARCHAR(50),--发送时间
    TYPE VARCHAR(4),--消息类别
    STYP VARCHAR(4) --消息类型
);
CREATE TABLE TEAM08.DFME_DEPE(
ID INT PRIMARY KEY IDENTITY(1,1),
META_ID NUMBER(6) REFERENCES TEAM08.COMMON_META(SEQN),--关联META
FLID VARCHAR,--航班标识标签
FATT VARCHAR,--航班属性
FFID VARCHAR,--航班标识
FIDE VARCHAR,--航班标识
STAT VARCHAR,--航班发布动态
ISTA VARCHAR,--航班状态
MSTA VARCHAR,--航班发布状态
MIST VARCHAR,--内部航班状态2
FRTT VARCHAR--实际起飞时间
);

CREATE TABLE TEAM08.DFME_DLYE(
ID INT PRIMARY KEY IDENTITY(1,1),
META_ID NUMBER(6) REFERENCES TEAM08.COMMON_META(SEQN),
FLID VARCHAR,--航班标识标签
FFID VARCHAR,--航班标识
FIDE VARCHAR,--航班标识
FATT VARCHAR,--航班属性
ABST VARCHAR,--航班不正常状态
IAST VARCHAR,--内部航班不正常状态
ABRS VARCHAR,--航班发布不正常原因
IARS VARCHAR,--内部航班不正常原因
MABS VARCHAR,--航班发布不正常状态2
MABR VARCHAR,--航班发布不正常原因2
MIAS VARCHAR,--内部航班不正常状态 2
MIAR VARCHAR,--内部航班不正常原因 2
FETT VARCHAR--航班预计时间
);

CREATE TABLE TEAM08.DFME_FETT(
ID INT PRIMARY KEY IDENTITY(1,1),
META_ID NUMBER(6) REFERENCES TEAM08.COMMON_META(SEQN),
FLID VARCHAR,--航班标识标签
FFID VARCHAR,--航班标识
FIDE VARCHAR,--航班标识
FETT VARCHAR,--航班预计时间
FELT VARCHAR--预计到达时间
);

CREATE TABLE TEAM08.DFME_FPTT(
ID INT PRIMARY KEY IDENTITY(1,1),
META_ID NUMBER(6) REFERENCES TEAM08.COMMON_META(SEQN),
FLID VARCHAR,--航班标识标签
FFID VARCHAR,--航班标识
FIDE VARCHAR,--航班标识
FPTT VARCHAR,--计划起飞时间
FPLT VARCHAR--计划降落时间
);

CREATE TABLE TEAM08.DFME_FRTT(
ID INT PRIMARY KEY IDENTITY(1,1),
META_ID NUMBER(6) REFERENCES TEAM08.COMMON_META(SEQN),
FLID VARCHAR,--航班标识标签
FFID VARCHAR,--航班标识
FIDE VARCHAR,--航班标识
FRTT VARCHAR,--实际起飞时间
FRLT VARCHAR--实际到达时间
);

CREATE TABLE TEAM08.DFME_GTLS_GATE(
GTNO VARCHAR,--登机门序号如果有<GATE>则 M
ID NUMBER(6) PRIMARY KEY,--登机门唯一标识
CODE VARCHAR,--登机门编号,如果有<GATE>则 M
GTAT VARCHAR,--登机门属性
ESTR VARCHAR,--预计开始使用时 间 , 如 果 有<GATE>则 M
EEND VARCHAR,--预计结束使用时 间 , 如 果 有<GATE>则 M
RSTR VARCHAR,--实际开始使用时 间 , 如 果 有<GATE>则 M
REND VARCHAR,--实际结束使用时 间 , 如 果 有<GATE>则 M
BTSC VARCHAR,--资源所属楼号,如 果 有 <GATE>则 M
DFLT_ID NUMBER(6) REFERENCES TEAM08.DFME_GTLS(FLID)
);

CREATE TABLE TEAM08.DFME_GTLS(
ID INT  IDENTITY(1,1),
META_ID NUMBER(6) REFERENCES TEAM08.COMMON_META(SEQN),
FLID NUMBER(6)PRIMARY KEY,--航班标识标签
FFID VARCHAR,--航班标识
FIDE VARCHAR,--航班标识
FATT VARCHAR--航班属性
);